// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Contrato
{
    public int Id { get; set; }

    public DateOnly FechaFin { get; set; }

    public DateOnly FechaInicio { get; set; }

    public int IdPersona { get; set; }

    public int IdEquipo { get; set; }

    public virtual Equipo IdEquipoNavigation { get; set; }

    public virtual Persona IdPersonaNavigation { get; set; }
}