// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Persona
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int Dni { get; set; }

    public DateOnly FechaNacimiento { get; set; }

    public int IdPais { get; set; }

    public virtual ICollection<Contrato> Contrato { get; set; } = new List<Contrato>();

    public virtual ICollection<Equipo> Equipo { get; set; } = new List<Equipo>();

    public virtual Pais IdPaisNavigation { get; set; }

    public virtual ICollection<Prueba> Prueba { get; set; } = new List<Prueba>();
}