// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Prueba
{
    public int Id { get; set; }

    public int CantEtapas { get; set; }

    public float KmTotales { get; set; }

    public int IdPersona { get; set; }

    public string Nombre { get; set; }

    public int AñoEdicion { get; set; }

    public virtual Persona IdPersonaNavigation { get; set; }

    public virtual ICollection<PruebaEquipo> PruebaEquipo { get; set; } = new List<PruebaEquipo>();
}