// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Models;

public partial class Equipo
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public int IdPais { get; set; }

    public int IdPersona { get; set; }

    public virtual ICollection<Contrato> Contrato { get; set; } = new List<Contrato>();

    public virtual Pais IdPaisNavigation { get; set; }

    public virtual Persona IdPersonaNavigation { get; set; }

    public virtual ICollection<PruebaEquipo> PruebaEquipo { get; set; } = new List<PruebaEquipo>();
}