// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Models;

public partial class PruebaEquipo
{
    public int Id { get; set; }

    public int Posicion { get; set; }

    public int IdPrueba { get; set; }

    public int IdEquipo { get; set; }

    public virtual Equipo IdEquipoNavigation { get; set; }

    public virtual Prueba IdPruebaNavigation { get; set; }
}